services:
  postgres:
    image: postgres:15-alpine
    container_name: bazalt_db
    # Использование переменных окружения из .env файла
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}" # По умолчанию 5432:5432, но можно изменить в .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Раскомментировано для инициализации БД
    healthcheck: # Проверка готовности БД
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT}" # По умолчанию 8080:80
    depends_on:
      postgres:
        condition: service_healthy # Ждем, пока Postgres не пройдет healthcheck
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app-network

# Определение томов (Volumes)
volumes:
  postgres_data:
  pgadmin_data:

# Определение сети (Network)
networks:
  app-network:
